### ISSUE TITLE
[Unexpected behavior] Quoted string in CSV gets divided in parts

### ISSUE THREAD

**Issue by jpmurray** [Rodenastyle/stream-parser#11]
Importing a large CSV, I encounter this line:

```
"artist","title","album"
"Jorge Ben","Mas, Que Nada!","Samba Esquema Novo"
```

That gets output as such:

```
[
  "artist" => "Jorge Ben",
  "title" => [
    [
      0 => "Mas",
      1 => " Que Nada!",
    ],
  "album" => "Samba Esquema Novo"
]
```

I don't think this is expected behavior, no? Since the string is in double quotes, it should be see as a single line.

**Comment by Rodenastyle** [comment]
Hello @jpmurray , it is the expected behavior, for CSV documents de parser autodetects comma separated listings on the same cell and parse them as an array. However, you can disable this feature overwriting the static $delimiters variable, of the CSVParser class.

**Comment by jpmurray** [comment]
OH! Good to know! ;-)
