### ISSUE TITLE
Segmentation fault parsing basic xml in php 7.2

### ISSUE THREAD

**Issue by MichaelCStevens** [Rodenastyle/stream-parser#18]
[Mon Dec 10 17:26:33.787959 2018] [core:notice] [pid 16515] AH00051: child pid 16568 exit signal Segmentation fault (11), possible coredump in /etc/apache2

**Comment by Rodenastyle** [comment]
This doesn't seems to be related with the package itself but your apache configuration. Anyway, we would have needed some more information about your configurations and parser usage to be able to reproduce the issue.

**Comment by MichaelCStevens** [comment]
Sorry for the late reply, but this was first observed in php's built in web server, and persisted in an apache environment as well. I assume the only configs that are related would be the php.ini file. Would that help? Could it be an issue with xdebug?
