### ISSUE TITLE
Not working with composer...

### ISSUE THREAD

**Issue by rickghome** [Rodenastyle/stream-parser#19]
I'm trying to use your parser in a laravel project. Installed via composer as instructed, but the parser class is not found during execution. Tried using your namespace, still no luck. Must be doing something trivially dumb, but I don't see it. Any suggestions?

**Comment by Rodenastyle** [comment]
Hmmm, `\Rodenastyle\StreamParser\StreamParser::xml()` maybe that required repetition of StreamParser? (First one is the namespace, second one the class itself)
